spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bank
    username: vlad
    password: vlad
    driver-class-name: org.postgresql.Driver

  jpa:
    properties.hibernate:
      hbm2ddl.auto: validate

  liquibase:
    change-log: classpath:liquibase/db.changelog.yaml
    enabled: true


security:
  jwt:
    secret: 2a$12$h/ZKTXJe3Y5uny5buQ5xJeMgH3mLttIWx.IqUPDFRBFBpZ2k08f/u